### ISSUE TITLE
Can't get eslint to find the rule

### ISSUE THREAD

**Issue by idolize** [eslint-plugins/eslint-plugin-lodash#1]
I tried following the guide (installing, adding to plugins and rules) and I always get the following error when I run eslint:

```
Error: Definition for rule 'lodash/import' was not found.
```

**Comment by AlexKVal** [comment]
I will release patch version with this fix. 
:cherries: 

Thank you for testing this library :wink:

**Comment by AlexKVal** [comment]
Sorry. There are some "technical" problems with `npm publish` :smile: 

## 

@mtscout6 I've got no rights to publish to this project's `npm` repo. :stuck_out_tongue_closed_eyes:

**Comment by mtscout6** [comment]
@AlexKVal Sorry about that I just added you as one of the npm owners for that package.

**Comment by AlexKVal** [comment]
@idolize I've just released fixed `v0.1.3`
:cherries: 

## 

@mtscout6 Thank you.
