### ISSUE TITLE
import-scope false positive with `lodash/fp`

### ISSUE THREAD

**Issue by SpainTrain** [eslint-plugins/eslint-plugin-lodash#10]
When using the `member` import style with the `import-scope` rule, imports from `lodash/fp` are incorrectly marked as errors.  E.g., 

```js
import {
    filter as fpFilter,
    map as fpMap,
} from 'lodash/fp'
```

reports `Import members from the full lodash module`

IIRC, `fp` will be moved to a different module in the next lodash major version, but for now I think this is incorrect behavior?  If agreed, I can probably work up a PR to fix it.

**Comment by SpainTrain** [comment]
derp! https://github.com/wix/eslint-plugin-lodash/issues/134

**Comment by krutoo** [comment]
@SpainTrain can you reopen this issue for implement fix on this repo?
